injection:
  dwarfs: null
  ingest: false
  mag_limit: 29
  mag_limit_band: LSST_g
  stamp_size: [600,600]
pipelines:
  bands: ['g','r','i']
  input_collection: HSC/runs/RC2/w_2023_32/DM-40356
  patch: 3
  repo: /repo/main
  skymap: hsc_rings_v1
  tract: 9615
sampling:
  n_dwarfs: 10
  params:
    age: 10
    dec: null
    distance: [2,3,'linear']
    ellipticity: [0,0.5, 'linear']
    feh: -2.0
    m_v: [-11,-5,'linear']
    r_scale: null
    ra: null
    sersic_index: 1
    stellar_mass: null
    surface_brightness: [24,27,'linear']
    x_cen: [300,3800,'linear']
    y_cen: [300,3800,'linear']
  output_file: "example_dwarf_params.csv"
  random_seed: null
  type: sample
