injection:
  dwarfs: null
  ingest: false
  mag_limit: 29
  mag_limit_band: LSST_g
  type: stamp

pipelines:
  bands: ['g','r','i']
  input_collections: ['HSC/runs/RC2/w_2023_32/DM-40356/20230819T003257Z']
  patch: 28
  repo: ./deepCoadd_repo
  skymap: hsc_rings_v1
  tract: 9615
sampling:
  n_dwarfs: 30
  params:
    age: 10
    dec: null
    distance: [2,3,'linear']
    ellipticity: [0,0.5, 'linear']
    feh: -2.0
    m_v: [-10,-4,'linear'] # this should go to -11
    r_scale: null
    ra: null
    n: 1
    theta: [0,180,'linear']
    stellar_mass: null
    surface_brightness: [24,28,'linear']
    x_cen: [300,3800,'linear']
    y_cen: [300,3800,'linear']
    random_seed_injection: null
  output_file: "example_dwarf_params.csv"
  output_directory: ./round_3_params/ 
  random_seed_sampling: null
  type: sample
stamp:
  directory: ./stamps/round_3/ # dont forget the trailing slash
  size: [600,600]
  title_format: hsc_stamp_r3
  Q: 10
  stretch: 0.5
  minimum: 0
  n_empty: 20
