# this config is intended to be used with the genrate_stamps_hyrax_v1.py script
injection:
  dwarfs: null
  ingest: false
  mag_limit_band: LSST_g
  inject_mag_limit: 36
  replace_mag_limit: 29
  type: stamp # using grid so that catalogs are concatenated per patch

pipelines:
  bands: ['g','r','i']
  input_collections: ['pdr3_deepCoadd']
  patch: None
  repo: /Volumes/gimli/hsc_pdr3/repo/hsc_pdr3
  skymap: hsc_rings_v1
  tract: None
sampling:
  generation_id: null
  n_dwarfs: None
  params:
    age: 10
    dec: null
    dist: [3.4,3.6,'linear'] # distance in Mpc
    ellip: [0,0.5, 'linear']
    feh: -2.0
    m_v: [-10,-5,'linear'] # this should go to -11
    r_scale: [1,3, 'loglinear']
    ra: null
    n_sersic: 1
    theta: [0,180,'linear']
    stellar_mass: null
    surface_brightness: null #[24,28,'linear'] # 24 to 28
    x_cen: None
    y_cen: None
    random_seed_injection: null
  output_file: None
  output_directory: /Volumes/gimli/hsc_pdr3/pferguson/dwarf_finder/data/hyrax_v1/dwarf_params/
  random_seed_sampling: null
  type: sample
stamp:
  type: single_band
  annotation: False
  annotation_scaling: None
  version: 1
  directory: /Volumes/gimli/hsc_pdr3/pferguson/dwarf_finder/data/hyrax_v1/stamps/ # dont forget the trailing slash
  size: [600,600]
  title_format: None 
  Q: None
  stretch: None
  minimum:  None
  mask_value: 0
  n_empty: 0
  
